name: CICD do nosso Projecto 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env01
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          sudo apt -y update
          sudo apt install -y postgresql-client
          echo ${{ secrets.PG_PASS }}
          echo ${{ vars.DB_HOST }}
          # Execute o comando psql
          PGPASSWORD=${{ secrets.PG_PASS }} psql -d db-mg -h ${{ vars.DB_HOST }} -U postgres -f listagem.sql
          
