name: CICD do nosso Projecto 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env01
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          sudo apt -y update
          sudo apt install -y postgresql-client
          echo ${{ secrets.PG_PASS }}
          echo ${{ vars.DB_HOST }}
          # Verifica se a variável DB_HOST não está vazia
          if [ -z "${{ vars.DB_HOST }}" ]; then
            echo "Erro: DB_HOST não está definido"
            exit 1
          fi
          # Execute o comando psql
          PGPASSWORD=${{ secrets.PG_PASS }} psql -d db-mg -h ${{ vars.DB_HOST }} -U marcogoncalves -c "\l" # Comando para listar bancos de dados, substitua conforme necessário
